source "https://rubygems.org"

gem "capybara", "3.33"

gem "cucumber", "5.2"

gem "selenium-webdriver", "3.142"

gem "rspec", "3.10"

gem "httparty", "0.18.1"

gem "pghero", "2.7.2"

gem "allure-cucumber", "2.13.6.4"

gem "rufo", "0.12.0"
